version: "3.9"

services:

    app:
        build:
            context: .
            dockerfile: Dockerfile
        environment:
            - API_KEY=modesto
        volumes:
            - ./data:/data
        command: uvicorn api:app --host 0.0.0.0 --port 8081
        ports:
            - "8081:8081"

    dashboard:
        build:
            context: .
            dockerfile: Dockerfile-dashboard
        volumes:
            - ./data:/data
        command: streamlit run user_intents_dashboard.py
        ports:
            - "8501:8501"
    # jupyterlab:
    #     build:
    #         context: .
    #         dockerfile: Dockerfile-research
    #     ports:
    #         - "8888:8888"
    #     volumes:
    #         - ./.docker/data:/opt/app/data
    #     entrypoint: sh -c "jupyter lab --ip=0.0.0.0 --port=8888 --no-browser --notebook-dir=/opt/app/data --allow-root --NotebookApp.token='' --NotebookApp.password=''"
